name: Pull Request on Github
on: [pull_request]
jobs: 
  PullRequest-Github:
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkou@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v2,0 
        with: 
            envkey_PORT: 5000
            envkey_SECRET: 'ba9ab35e92f49929338ad8247b06a6df752ace8129502db0bd5cfb78bd71fcc7'
            envkey_DATABASE_URL: 'mongodb+srv://admin:admin-test@cluster0.egtbg.mongodb.net/marketplace-test?retryWrites=true&w=majority&appName=Cluster0'
            directory: ./
            file_name: .env.test
            fail_on_empty: true
      - name: Run tests backend
        run: docker compose -f docker-compose-test.yml run node npm run test
